### ISSUE TITLE
numberRecords to large

### ISSUE THREAD

**Issue by thomasstjerne** [gbif/occurrence#29] opened 2018-01-16 14:27 UTC
numberRecords given in some of the results is exceeding the total number of records in the dataset.

https://api.gbif.org/v1/occurrence/download/dataset/84d26682-f762-11e1-a439-00145eb45e9a?limit=20&locale=en&offset=0

**Comment by MattBlissett** [comment] 2019-07-04 07:39
Duplicate of https://github.com/gbif/portal-feedback/issues/1659

**Closed by MattBlissett** 2019-07-04 07:39 UTC
