### ISSUE TITLE
log in meta.xml of GBIF annotated archive

### ISSUE THREAD

**Issue by MortenHofft** [gbif/occurrence#56] opened 2018-07-12 10:17 UTC
from @data-biodiversity-aq

Hello, 

I found some logging in `meta.xml` of GBIF annotated archive downloaded today. Could you please have a look at it?

Link to this archive: [https://www.gbif.org/occurrence/download/0042221-180508205500799](https://www.gbif.org/occurrence/download/0042221-180508205500799) 

Or here: [0042221-180508205500799.zip](https://github.com/gbif/portal16/files/2187984/0042221-180508205500799.zip)

The log looks like this:
```
<archive xmlns="http://rs.tdwg.org/dwc/text/" metadata="metadata.xml">
  <core encoding="UTF-8" fieldsTerminatedBy="\t" linesTerminatedBy="\n" fieldsEnclosedBy="" ignoreHeaderLines="1" rowType="FreeMarker template error (DEBUG mode; use RETHROW in production!):
The following has evaluated to null or missing:
==> core.rowType.qualifiedName  [in template "meta.ftl" at line 4, column 315]

----
Tip: It's the step after the last dot that caused this error, not those before it.
----
Tip: If the failing expression is known to be legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
----

----
FTL stack trace ("~" means nesting-related):
	- Failed at: ${core.rowType.qualifiedName()} auto-...  [in template "meta.ftl" at line 4, column 313]
----

Java stack trace (for programmers):
----
freemarker.core.InvalidReferenceException: [... Exception message was already printed; see it above ...]
```

Thank you so much.

**Comment by MattBlissett** [comment] 2018-08-01 15:33
Duplicate of https://github.com/gbif/portal-feedback/issues/1464, now fixed.

**Closed by MattBlissett** 2018-08-01 15:33 UTC
Labels: bug
